BugFix:
Found a Bug, and fixed it: The game freezes on ENEMY TURN.

Reason of the bug: Very complex Pathfinding calculations to be able to shoot a grenade with the less number of steps.

On method: "GetEnemyAIActionData" the game finds a NullReferenceException, because the original design of the function was taking into consideration ONLY GridPositions filled up with an Unit (a character). But GrenadeAction.cs asks to be able to fire to "vacant" spots, to destroy Props such as: Doors, Walls, Crates, etc, which we just designed in the previous commit.

   The solution was adding a simple NULL-CHECK to "GetEnemyAIActionData".

---- Text of the Error / Bug ---

NullReferenceException: Object reference not set to an instance of an object
GrenadeAction.GetEnemyAIActionData (GridPosition gridPosition, System.Int32 initialAdditionalAIActionPointCostValueOfThisAction) (at Assets/Scripts/MainGame/Actions/GrenadeAction.cs:140)
BaseAction.GetBestEnemyAIActionData () (at Assets/Scripts/MainGame/Actions/BaseAction.cs:326)
EnemyAI.TryTakeEnemyAIAction (UnitEnemy enemyUnit, System.Action onEnemyAIActionComplete) (at Assets/Scripts/MainGame/AI/EnemyAI.cs:754)
EnemyAI.TryTakeEnemyAIAction (System.Action onEnemyAIActionComplete) (at Assets/Scripts/MainGame/AI/EnemyAI.cs:637)
EnemyAI.TryToMakeAGeneralBestDecision (System.Action onEnemyAIActionComplete) (at Assets/Scripts/MainGame/AI/EnemyAI.cs:295)
EnemyAI.Update () (at Assets/Scripts/MainGame/AI/EnemyAI.cs:191)

----END OF:  Text of the Error / Bug ---