Final Level
1- Created a complete level 1.
W.I.P., 70%

2- Need to solve Bug: When an Unit is defeated, for some reason we see a NUllReferenceException meaning that the Unit GameObject is destroyed, but at the same time we are trying to access it to get its GidPosition.

The Error is similar to:

MissingReferenceException: The object of type 'UnitEnemy' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Unit.GetWorldPosition () (at Assets/Scripts/MainGame/Unit.cs:517)
UnitAnimator.ShootAction_OnShootAnimation (System.Object sender, ShootAction+OnShootAnimationEventArgs e) (at Assets/Scripts/MainGame/UnitAnimator.cs:223)
ShootAction.Shoot () (at Assets/Scripts/MainGame/Actions/ShootAction.cs:390)
ShootAction.Update () (at Assets/Scripts/MainGame/Actions/ShootAction.cs:253)

---

My guess:

The object is aready killed and removed from the scene... and the physics of the Bullet is waving in and out of the error tolerance value, triggering the "kill animation process" multiple times, and generating that error.